name = "fad"
version = "0.1.0"
defaultTargets = ["Fad"]

[[lean_lib]]
name = "Fad"

[[lean_exe]]
name = "main"
root = "Main"

[[require]]
name = "cslib"
git = "https://github.com/kim-em/cslib"
rev = "391cab007c5c056af9ab874e450fc91a9e9daee5"
